theme: hugo-theme-re-terminal
baseURL: http://gabrielbryer.com/
languageCode: en-us
title: Gabriel Bryer
publishDir: docs

params:
  contentTypeName: posts
  themeColor: blue
  showMenuItems: 3
  fullWidthTheme: false
  centerTheme: true
  # banner:
  #   dismissible: false
  #   text: Check it out on GitHub
  #   url: 'https://github.com/mirus-ua/hugo-theme-re-terminal'
pagination:
  disableAliases: false
  pagerSize: 10
  path: page
languages:
  en:
    params:
      title: Gabriel Bryer
      subtitle: ''
      keywords: ''
      copyright: ''
      menuMore: Show more
      readMore: Read more
      readOtherPosts: Read other posts
      logo:
        logoText: Gabriel Bryer
        logoHomeLink: /
    menu:
      main:
        # - identifier: submenu
        #   name: Sub menus
        #   weight: 10
        - identifier: subabout
          name: About Me
          url: /about
        # - identifier: subshowcase
        #   name: Showcase
        #   url: /showcase
        #   parent: submenu
        # - identifier: about
        #   name: About
        #   url: /about
        # - identifier: showcase
        #   name: Showcase
        #   url: /showcase
